connection: mysql
host: 127.0.0.1
user: statping
password: e7jFyDcg7Ly6JG5R
database: statping
port: 3306
language: en
allow_reports: true
location: /opt/statping
disable_http: false
demo_mode: false
disable_logs: false
use_assets: false
sample_data: false
use_cdn: false
disable_colors: false
