language: python
python:
  - "3.5"
env:
  - HTTPOBS_BROKER_URL="fakebrokerurl" HTTPOBS_DATABASE_HOST="fakehost" HTTPOBS_DATABASE_PASS="foo" HTTPOBS_DATABASE_USER="bar"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - "nosetests httpobs/tests -e insert_test_result -e scored_test -e select_test_results -e test_retrieve --with-coverage --cover-package=httpobs"
stage: test
stages:
  - name: test
    if: type != cron
  - name: cron
    if: type = cron  
jobs:
  include:
    - stage: test
    - stage: cron
      after_success: .travis/cron.sh
